# Generated by Django 5.2.11 on 2026-05-07 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_placa', models.CharField(max_length=10, unique=True, verbose_name='Número de Placa')),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobros.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['numero_placa'],
            },
        ),
    ]
