# Generated by Django 5.2.11 on 2026-05-07 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0002_vehiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_espacio', models.CharField(max_length=10, unique=True, verbose_name='Número de Espacio')),
                ('tipo_espacio', models.CharField(choices=[('normal', 'Normal'), ('vip', 'VIP'), ('discapacitado', 'Discapacitado')], default='normal', max_length=20, verbose_name='Tipo de Espacio')),
                ('vehiculo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cobros.vehiculo', verbose_name='Vehículo Asignado')),
            ],
            options={
                'verbose_name': 'Espacio',
                'verbose_name_plural': 'Espacios',
                'ordering': ['numero_espacio'],
            },
        ),
    ]
