# Generated by Django 5.2.11 on 2026-05-07 19:37

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0003_espacio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('tiempo_horas', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Tiempo en Horas')),
                ('costo_por_hora', models.DecimalField(decimal_places=2, default=Decimal('0.75'), max_digits=6, verbose_name='Costo por Hora')),
                ('precio_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Total')),
                ('cliente_nombre', models.CharField(max_length=100, verbose_name='Nombre Cliente')),
                ('cliente_apellido', models.CharField(max_length=100, verbose_name='Apellido Cliente')),
                ('cliente_email', models.EmailField(max_length=254, verbose_name='Email Cliente')),
                ('cliente_telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono Cliente')),
                ('cliente_dni', models.CharField(max_length=20, verbose_name='DNI Cliente')),
                ('vehiculo_numero_placa', models.CharField(max_length=10, verbose_name='Placa Vehículo')),
                ('vehiculo_color', models.CharField(max_length=50, verbose_name='Color Vehículo')),
                ('vehiculo_modelo', models.CharField(max_length=100, verbose_name='Modelo Vehículo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobros.cliente', verbose_name='Cliente')),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobros.espacio', verbose_name='Espacio')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobros.vehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Cobro',
                'verbose_name_plural': 'Cobros',
                'ordering': ['-fecha'],
            },
        ),
    ]
