# Generated by Django 5.2.11 on 2026-05-07 19:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0004_cobro'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(default='MARCA', max_length=100, verbose_name='Marca'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cobro',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10, verbose_name='Precio Total'),
        ),
        migrations.AlterField(
            model_name='espacio',
            name='tipo_espacio',
            field=models.CharField(choices=[('vehiculo', 'Vehiculo'), ('moto', 'Moto'), ('discapacitado', 'Discapacitado')], default='normal', max_length=20, verbose_name='Tipo de Espacio'),
        ),
    ]
