# Generated by Django 5.2.11 on 2026-05-07 20:11

import datetime
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0005_vehiculo_marca_alter_cobro_precio_total_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cobro',
            options={'ordering': ['-hora_ingreso'], 'verbose_name': 'Cobro', 'verbose_name_plural': 'Cobros'},
        ),
        migrations.RemoveField(
            model_name='cobro',
            name='fecha',
        ),
        migrations.AddField(
            model_name='cobro',
            name='hora_ingreso',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 5, 7, 20, 11, 13, 462053, tzinfo=datetime.timezone.utc), verbose_name='Hora de Ingreso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cobro',
            name='hora_salida',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora de Salida'),
        ),
        migrations.AlterField(
            model_name='cobro',
            name='cliente_apellido',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido Cliente'),
        ),
        migrations.AlterField(
            model_name='cobro',
            name='cliente_dni',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='DNI Cliente'),
        ),
        migrations.AlterField(
            model_name='cobro',
            name='cliente_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Cliente'),
        ),
        migrations.AlterField(
            model_name='cobro',
            name='cliente_nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Cliente'),
        ),
        migrations.AlterField(
            model_name='cobro',
            name='tiempo_horas',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=6, verbose_name='Tiempo en Horas'),
        ),
        migrations.AlterField(
            model_name='cobro',
            name='vehiculo_color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Color Vehículo'),
        ),
        migrations.AlterField(
            model_name='cobro',
            name='vehiculo_modelo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo Vehículo'),
        ),
        migrations.AlterField(
            model_name='cobro',
            name='vehiculo_numero_placa',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Placa Vehículo'),
        ),
    ]
