# Generated by Django 5.2.11 on 2026-05-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0006_alter_cobro_options_remove_cobro_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobro',
            name='hora_ingreso',
            field=models.DateTimeField(null=True, verbose_name='Hora de Ingreso'),
        ),
    ]
